
GET http://localhost:3000/
###


GET http://localhost:3000/signup
###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "Donald J. Trump",
    "email": "Donald.trump@gov.us",
    "password": "secret"
}
###


GET http://localhost:3000/signin
###

POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "Donald.trump@gov.us",
    "password": "secret"
}
###


GET http://localhost:3000/article
###

GET http://localhost:3000/users
###

GET http://localhost:3000/profile/1
###
